name: flutter_native_timezone
description: A flutter plugin for getting the local timezone of the device.
version: 2.0.1
homepage: https://github.com/pgahq/flutter_native_timezone

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.pgahq.flutter_native_timezone
        pluginClass: FlutterNativeTimezonePlugin
      ios:
        pluginClass: FlutterNativeTimezonePlugin
      macos:
        pluginClass: FlutterNativeTimezonePlugin
